### ISSUE TITLE
gst: Known issues

### ISSUE THREAD

**Issue by thiblahute** [hotdoc/hotdoc_c_extension#6]
# Todo tasks

- [ ] Offset headers in comments
- [ ] Fix links in https://thiblahute.github.io/GStreamer-doc/doc_index.html?gi-language=python
- [ ] Toc in https://people.collabora.com/~meh/GStreamer-doc/playback-1.0/playbin.html?gi-language=python#playbin-page is ugly

---

# Done tasks:

- [x] https://thiblahute.github.io/GStreamer-doc/pango-1.0/clockoverlay.html -> unicode issue, Tim-Philipp M?ller 
- [x] Link to https://people.collabora.com/~meh/GStreamer-doc/GStreamer-core-plugins-1.0/valve.html?gi-language=python#valve point to the end of the page (this link is from https://people.collabora.com/~meh/GStreamer-doc/GStreamer-core-plugins-1.0/index.html?gi-language=python)
- [x] Fix diffs in json caches
- [x] https://thiblahute.github.io/GStreamer-doc/libgstreamer-1.0/gsttaskpool.html?gi-language=python#callbacks should be hiden `In [4]: Gst.TaskPoolFunction ->NotImplementedError: gi.CallbackInfo(TaskPoolFunction)`
- [x] https://thiblahute.pages.gitlab.gnome.org/gnome-devel-docs/app-1.0/appsink.html?gi-language=c#properties -> "self.props" ?!
- [x] Colision between https://thiblahute.github.io/GStreamer-doc/gst-plugins-base-app-1.0/c/gstappsink.html#GstAppSink:max-buffers and https://thiblahute.github.io/GStreamer-doc/app-1.0/appsink.html#GstAppSink:max-buffers
- [x] When scrolled down and searching, we need to scroll back up to see the results
- [x] In the sitemap click on the current page -> 404
- [x] Handle structures with method/construct infos as if they were objects in the rendering.
- [x] When going to [GstStructure](https://thiblahute.github.io/GStreamer-doc/libgstreamer-1.0/c/gststructure.html#gststructure-1) the ToC is not expending
- [x] When toggling API Version, the ToC gets crazy
- [x] In [GstBin.add_element](https://thiblahute.github.io/GStreamer-doc/libgstreamer-1.0/c/gstbin.html#GstBinVirtual_Methods) there is no blurb!
- [x] Signal signatures are broken (they do **not** contain the `self` object) e.g [GstRTSPMediaFactory::media-configure](https://thiblahute.github.io/GStreamer-doc/gst-rtsp-server-1.0/c/rtsp-media-factory.html#mediaconfigure)
- [x] https://thiblahute.github.io/GStreamer-doc/gst-plugins-base-video-1.0/c/video-format.html#gstvideoformatpack doesn't land at the correct position in the page (link was wrong)
- [x] `gchar **` are rendered as [utf8*](https://thiblahute.github.io/GStreamer-doc/libgstreamer-1.0/c/gsturi.html#gst_uri_handler_get_protocols)
- [x] https://thiblahute.github.io/GStreamer-doc/libgstreamer-1.0/c/Miscellaneous.html#gstpad -- why are those signal in misc?
- [x] in [GESPipeline.props.mode](https://thiblahute.github.io/GStreamer-doc/gst-editing-services-1.0/python/ges-pipeline.html#mode) the link to [ges_pipeline_set_mode](https://thiblahute.github.io/GStreamer-doc/gst-editing-services-1.0/python/ges-pipeline.html#gespipelineset_mode) is of `#gespipelineset_mode` VS `#ges_pipeline_set_mode` -- anchor links look wrong.
- [x] Search for `gst_util_get_timestamp`, the actual symbol doesn't show up in the search results
- [x] https://thiblahute.github.io/GStreamer-doc/gst-plugins-base-riff-1.0/riff-media.html
- [x] https://thiblahute.pages.freedesktop.org/gst-build/gst-plugins-base-sdp-1.0/gstsdpmessage.html?gi-language=c#GstSDPConnection , TOC has a lot of top-level methods sections

**Comment by ndufresne** [comment]
I discovered that Since marker checks don't work with the c-index, which I believe is using this extension. Porting the library to gi-index seems to fix the problem.
